name = "next-project-programs"
version = "0.1.0"
authors = [""]

[[programs]]
path = "src/main.py"
name = "main"
prime_size = 128

[[programs]]
path = "src/blind_bidding.py"
name = "blind_bidding"
prime_size = 128